stages:
  get_data:
    always_changed: true
    wdir: ../
    cmd: python pipelines/get-data.py
    deps:
      - pipelines/get-data.py
    outs:
      - data/temp/constituencies.csv:
          cache: false
          persist: true
  rank:
    wdir: ../
    cmd: python pipelines/rank.py
    deps:
      - pipelines/rank.py
      - data/temp/constituencies.csv
    outs:
      - src/_data/ranked_constituencies.json:
          cache: false
          persist: true
      - src/_data/ranked_constituencies.csv:
          cache: false
          persist: true
