name: Update data

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1' # Runs at 9am on a Monday
  push: 
    branches: [ main ]
    paths:
      - 'pipelines/**'
      - 'data/**'
      - '.github/workflows/update-data.yml'

jobs:
  # Update data job
  update:
    name: Update data and commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: pipenv

      - name: Setup pipenv
        shell: bash
        run: |
          pip install pipenv
          pipenv install

      - name: Run pipelines
        run: |
          pipenv run dvc repro -R pipelines
      
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Run pipelines
          file_pattern: data pipelines src